### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by LoneDevilX** [flokol120/Spigot-Item-Chest-Sorter#15]
The item chest sorter are manually open&close to active the sorter system.

Is it available / possible to make it without manual active? Can it be automatic?

**Comment by flokol120** [comment]
@LoneDevilX I hope I understood your question correctly: Items are send when somebody closes a sender chest, a hopper places items into a sender chest und when a receiver puts items into a sender chest (only if this experimental feature is enabled in the config.yml).

**Comment by LoneDevilX** [comment]
Hm... What I mean is , the items will only be transferred if we manually open & close the hopper/chest (sender).

Can It be automatically rather than we need to manually open & close.

**Comment by flokol120** [comment]
Items are moved on the InventoryMoveItemEvent, which should be "automatic" in your case. Maybe give me an example on what you are trying to achieve (eg. how are you putting items in the chest).

**Comment by LoneDevilX** [comment]
Oh... The items are either move by Vanilla hopper / another 'RECEIVER' ( can sender A become Receiver B also?).

Sender A = Receiver B

the Sender A wanted to transfer diamond to Receiver A
The Sender A chest will be filled by Vanilla hopper / Sender B

Sender A will be full and unable to move the item to Receiver A if I didn't manually open & close

**Comment by flokol120** [comment]
Your example should work as a vanilla hopper triggers the InventoryMoveItemEvent when passing items to a sender chest. What version are you using? 
It is possible to chain senders and receiver systems, yes. This feature however should not be used on a public server for now because you could create loops that would eventually crash the whole server. On a private server this feature can be used, but with caution.

**Comment by LoneDevilX** [comment]
My example should work as 
When a vanilla hopper transfer items into Sender Chest, then sender chest should automatically trigger the InventoryMoveItemEvent & pass to Receiver Chest

I am a public server using version Paper 1.15.2 .

**Comment by flokol120** [comment]
I mean which version of the plugin are you using :stuck_out_tongue_winking_eye:

**Comment by LoneDevilX** [comment]
Bruh hahahahha
I am using the latest one just downloaded from Github.

**Comment by flokol120** [comment]
Alright. I'll investigate your issue further. But I can't tell when I have time to do so.

**Comment by LoneDevilX** [comment]
> Alright. I'll investigate your issue further. But I can't tell when I have time to do so.

No worry, anyway is there any further/convenience way to reach you rather than Github?

**Comment by flokol120** [comment]
Hi @LoneDevilX,
please share your config.yml with me for further investigations.

And no there is no other contact possibility as I'd like to keep such dialogs on GitHub for others who may have the same issue.

**Comment by LoneDevilX** [comment]
[Item-Chest-Sorter.zip](https://github.com/flokol120/Spigot-Item-Chest-Sorter/files/5296060/Item-Chest-Sorter.zip)

Okay

**Comment by flokol120** [comment]
@LoneDevilX
I investigated your issue by using the same config.yml and chests.json. However it was working perfectly fine on my end. This leads me to believe that this issue is due to Paper. I do not officially support Paper and I do not know enough about it to investigate your issue further. Sorry about that :(. My suggestion: Try to Send the items this way A Sender --> A Receiver AND B Sender --> B Receiver. Maybe this works for you. If not I unfortunately cannot help you any further.

**Comment by LoneDevilX** [comment]
The vanilla hopper --> Sender A , it still automatically send to Receiver A? (Without manually open&Close?)

**Comment by flokol120** [comment]
@LoneDevilX This is working for me, yes.

**Comment by LoneDevilX** [comment]
Oh okay.. may I ask when will this plugin officially support Paper?

**Comment by flokol120** [comment]
@LoneDevilX No, I don't think I have time to read through their docs to figure this issue out. Closing for now.
