### ISSUE TITLE
Suggestion - multi receiver single chest option

### ISSUE THREAD

**Issue by EchocallingEarth** [flokol120/Spigot-Item-Chest-Sorter#22]
May I suggest the addition of multi receiver chest. Meaning if a chest has more then 1 item frame attached to it and it is a receiver chest it will receive the items in those frames as well. 
Currently only the front facing or main item frame is used to sort and accept items. It would be nice if we could attach say 4 frames each with a different item and those be sorted to the same chest.

This would of course make it more of an advanced item sorter system but it would also allow putting say all cooked foods in one chest or all veggies in one chest etc.

Note only item frames placed on the front, sides and back of chest should work I think for this feature. semi restricting its use.

I can try to give more info etc if this is something that may be considered. - Thank you

**Comment by flokol120** [comment]
@EchocallingEarth I like the idea :thinking: But I do not have enough time to implement your feature request at the moment, due to lack of free time :P. But be assured, I will keep it in mind. For the moment I can only suggest you to take a look into the regex section in the config file. There is a way to sort all cooked items as in your example.
I will just leave this here for now:
`sets:
# example 1.1: Move all wool colors to the same chest (using explicit all ids)
# remove the '#' in the next two lines if you want to move all different colored wool blocks into one chest
#  - [white_wool, orange_wool, magenta_wool, light_blue_wool, yellow_wool, lime_wool, pink_wool, gray_wool,
#  light_gray_wool, cyan_wool, purple_wool, blue_wool, brown_wool, green_wool, red_wool, black_wool]

# example 1.2: Move all wool colors to the same chest (using regex)
# remove the '#' in the next line if you want to move all different colored wool blocks into one chest
#  - ['.*_wool']

# example 2: Move all flowers to the same chest
# remove the '#' in the next two lines if you want to move all different flowers into one chest
#  - [dandelion, poppy, blue_orchid, allium, azure_bluet, red_tulip, orange_tulip, white_tulip, pink_tulip,
#  oxeye_daisy, cornflower, lily_of_the_valley, wither_rose, sunflower, lilac, rose_bush, peony]`

**Comment by flokol120** [comment]
@EchocallingEarth good news: I finally had time for this. I don't know if you still cared about this, but I said I'll keep you posted :D

This is present in 1.13.0
