### ISSUE TITLE
[BUG] 1.20.2 returning error upon closing chest

### ISSUE THREAD

**Issue by j4c3** [flokol120/Spigot-Item-Chest-Sorter#52]
**Describe the bug**
[20:09:27 ERROR]: Could not pass event InventoryCloseEvent to Item-Chest-Sorter v1.14.2
java.lang.ClassCastException: class org.bukkit.craftbukkit.v1_20_R2.block.CraftBlockState cannot be cast to class org.bukkit.block.Container (org.bukkit.craftbukkit.v1_20_R2.block.CraftBlockState and org.bukkit.block.Container are in unnamed module of loader java.net.URLClassLoader @277050dc)

**Version Information**
- Minecraft Version: 1.20.2
- Server Flavor: Paper (build 238)
- Plugin Version 1.14.2

**Comment by flokol120** [comment]
@j4c3 This error has nothing to do with 1.20.2 itself. It happens if you added a receiver chest but removed it afterwards. Destroyed Receiver chests are not automatically removed as receivers. However, there is an open feature request which is not yet implemented (#48).

To prevent this from happening in the future, enable `allowBreakOfChest: true` within the config.yml. As the name suggests, it prevents the removal of chests specified as either a sender or a receiver.

To mitigate this error for now, I'll publish an update which will log a message to the server log, if a chest is missing. It will print out the chests coordinates as well as the generated ID. That way you can either replace the chest by using the coordinates or delete the chest from the Item Chest Sorter plugin using `/ics remove [receiver/sender] <ID>`.

**Comment by flokol120** [comment]
fixed in [1.14.3](https://github.com/flokol120/Spigot-Item-Chest-Sorter/releases/tag/1.14.3)
