### ISSUE TITLE
using redstone-signal

### ISSUE THREAD

**Issue by pigvader** [flokol120/Spigot-Item-Chest-Sorter#9]
I use a hopper to put my items in the sender chest.
So,  is it possible that the items are sorted using a redstone signal?
currently i have to put my stuff in the sender chest and It's a bit cumbersome in the long run

**Comment by flokol120** [comment]
Which version are you using?
Sender chests are able to accept items from hopper. This feature is enableable in the config.yml.

**Comment by pigvader** [comment]
Hi
ich habe die neuste Version von dir und die MC Version 1.15.2
Das Ding ist folgendes:

Ich benutze ein Plugin um von einem Hopper die Items in eine Chest zu transferieren ("wireless"). Zwischen dieser Chest und der Sender-Chest ist ein Hopper. In der config habe ich die Option mit dem Hopper aktiviert. Allerdings muss ich dennoch jedes Mal "in die Kiste gucken" damit der Inhalt wegsortiert wird. 
Der Gedanke war hier nur, dass per Redstonesignal diese Handlung nicht notwendig ist. 

Ich hoffe ich habe das nicht verwirrend erklärt ^^

**Comment by flokol120** [comment]
@pigvader please keep this in english. Otherwise other people cannot follow if they are facing the same issue.
This is very strange. Here are some questions to troubleshoot your stated behavior:
Have you reloaded/restarted the server after making the change to the config.yml?
What happens if you manually put items into the chest which is connected by a hopper to your sender chest? Are the items then automatically send to your receiver chest(s)?
My first guess here is that the plugin you use for transferring the items does not call the onInventoryMoveEvent.
If my assumption is right there is nothing to do for me as this is a mistake in the other plugin you are using.

**Comment by pigvader** [comment]
sorry, then in English ;-)

I found the mistake...
It was because of my poor intelligence.
I made a mistake in Set 1.1 in config.
As a result, the config was not loaded.

Fixed the bug and now it works.

Thanks for the hint :)

**Comment by flokol120** [comment]
Alright. At least you had the intelligence to find the error by yourself :stuck_out_tongue:

Just an idea...: You can also use this plugin to transport items from a hopper to a container (container = chest, barrel, hopper, ...). This way you could get rid of the other plugin to save some server resources. (This is possible since the latest version and not fairly well documented. I will have to update the description on the spigot forum as soon as I got time)
